# Generated by Django 4.0.3 on 2022-03-28 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Book', '0003_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='buy',
            field=models.ManyToManyField(related_name='buy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='devotes',
            field=models.ManyToManyField(related_name='dev', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='downloads',
            field=models.ManyToManyField(related_name='down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='reads',
            field=models.ManyToManyField(related_name='reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.ManyToManyField(related_name='upv', to=settings.AUTH_USER_MODEL),
        ),
    ]
