# Generated by Django 4.0.3 on 2022-03-30 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Book', '0004_post_buy_post_devotes_post_downloads_post_reads_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='Book.post')),
                ('saved', models.ManyToManyField(related_name='saved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
