# Generated by Django 4.0.3 on 2022-04-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_post_fav_delete_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Price',
            new_name='HPrice',
        ),
        migrations.AddField(
            model_name='post',
            name='SPrice',
            field=models.IntegerField(default=0),
        ),
    ]
