# Generated by Django 4.0.3 on 2022-04-20 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0007_rename_price_post_hprice_post_sprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='devotes',
        ),
        migrations.AddField(
            model_name='post',
            name='Language',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='PublishedIn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
