# Generated by Django 4.0.3 on 2022-04-20 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0009_alter_post_publishedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PublishedIn',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
