# Generated by Django 4.0.3 on 2022-04-20 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0011_alter_post_publishedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PublishedIn',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
