# Generated by Django 4.0.3 on 2022-04-27 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0015_alter_post_publishedin_alter_post_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PublishedIn',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_uploaded',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
